In [1]:
from os.path import join

import numpy as np 
import pandas as pd


/users/k/karmimy/anaconda3/envs/DGT/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


## UCI-Message


In [2]:
path_dst = '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets'
datadir = 'UCI-Message'
path_dst = join(path_dst, datadir)
file_save = join(path_dst,'ml_UCI-Message.csv')

In [3]:
path_src = '/share/DEEPLEARNING/datasets/graph_datasets/Rol'
file_src = 'CollegeMsg.txt'
path_src = join(path_src, file_src)

In [4]:
df = pd.read_csv(path_src,sep=' ',header=None)

In [5]:
df

0     1           2
0         1     2  1082040961
1         3     4  1082155839
2         5     2  1082414391
3         6     7  1082439619
4         8     7  1082439756
...     ...   ...         ...
59830  1899  1847  1098776648
59831  1899  1097  1098776836
59832  1899   277  1098777003
59833  1878  1624  1098777111
59834  1878  1624  1098777142

[59835 rows x 3 columns]

In [6]:
arr = df.values

In [7]:
ts = arr[:,2]

In [8]:
ts.min()

1082040961

In [9]:
ts.max()

1098777142

In [10]:
ts.max() - ts.min()

16736181

192369

In [34]:
delta = (ts.max() - ts.min()) // 87

In [35]:
interval = []
st = min(ts) + delta
while st < max(ts):
    interval.append(st)
    st += delta

In [36]:
len(interval)

87

In [37]:
start = min(ts)
dict_inter = {}
discretized_ts = []

for l in arr:
    t = l[2]
    for i,inter in enumerate(interval):
        if t < inter:
            discretized_ts.append([l[0],l[1],i])
            if i in dict_inter.keys():
                dict_inter[i] += 1
            else:
                dict_inter[i] = 1
            break
    else:
        discretized_ts.append([l[0],l[1],len(interval)])
        if i in dict_inter.keys():
            dict_inter[i] += 1
        else:
            dict_inter[i] = 1
    

In [38]:
new_arr = np.array(discretized_ts)

In [39]:

weight = np.zeros(len(new_arr),dtype=int)


In [40]:
weight

array([0, 0, 0, ..., 0, 0, 0])

In [41]:
new_arr = np.column_stack((new_arr, weight))

In [42]:
new_arr

array([[   1,    2,    0,    0],
       [   3,    4,    0,    0],
       [   5,    2,    1,    0],
       ...,
       [1899,  277,   86,    0],
       [1878, 1624,   87,    0],
       [1878, 1624,   87,    0]])

In [43]:
len(np.unique(new_arr[:,:2]))

1899

In [44]:
len(new_arr)

59835

In [45]:
new_df = pd.DataFrame(new_arr, columns=['u', 'i', 'ts','label'])

In [46]:
new_df.ts.to_numpy()

array([ 0,  0,  1, ..., 86, 87, 87])

In [47]:
len(np.unique(new_df.ts.to_numpy()))

88

In [48]:
new_df.to_csv(file_save, index=False) 

## Bitcoin Alpha 

In [21]:
path_dst = '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets'
datadir = 'Bitcoin-Alpha'
path_dst = join(path_dst, datadir)
file_save = join(path_dst,'ml_Bitcoin-Alpha.csv')

In [22]:
path_src = '/share/DEEPLEARNING/datasets/graph_datasets/Rol'
file_src = 'bitcoinalpha.csv'
path_src = join(path_src, file_src)

In [23]:
df = pd.read_csv(path_src,sep=',',header=None)

In [24]:
df

0     1   2           3
0      7188     1  10  1407470400
1       430     1  10  1376539200
2      3134     1  10  1369713600
3      3026     1  10  1350014400
4      3010     1  10  1347854400
...     ...   ...  ..         ...
24181  7604  7601  10  1364270400
24182  7601  7604  10  1364270400
24183  7604  7602  10  1364270400
24184  7602  7604  10  1364270400
24185  7604  7603 -10  1364270400

[24186 rows x 4 columns]

In [25]:
len(df)

24186

In [26]:
len(df)

24186

In [27]:
arr = df.values

In [28]:
arr

array([[      7188,          1,         10, 1407470400],
       [       430,          1,         10, 1376539200],
       [      3134,          1,         10, 1369713600],
       ...,
       [      7604,       7602,         10, 1364270400],
       [      7602,       7604,         10, 1364270400],
       [      7604,       7603,        -10, 1364270400]])

In [29]:
ts = arr[:,3]

In [30]:
ts

array([1407470400, 1376539200, 1369713600, ..., 1364270400, 1364270400,
       1364270400])

In [31]:
min(ts)

1289192400

In [32]:
b = max(ts)

In [33]:
deb = 1289088000
fin = 1453334400

In [37]:
interval = []
st = deb + 2*week
while st < fin:
    interval.append(st)
    st += 2*week

In [38]:
len(interval)

135

In [39]:
len(interval)

135

In [40]:
arr

array([[      7188,          1,         10, 1407470400],
       [       430,          1,         10, 1376539200],
       [      3134,          1,         10, 1369713600],
       ...,
       [      7604,       7602,         10, 1364270400],
       [      7602,       7604,         10, 1364270400],
       [      7604,       7603,        -10, 1364270400]])

In [41]:
start = deb # 7 novembre 2010 
# fin # 21 Janvier 2016
dict_inter = {}
discretized_ts = []

for l in arr:
    t = l[3]
    for i,inter in enumerate(interval):
        if t < inter:
            discretized_ts.append([l[0],l[1],l[2],i])
            if i in dict_inter.keys():
                dict_inter[i] += 1
            else:
                dict_inter[i] = 1
            break
    else:
        discretized_ts.append([l[0],l[1],l[2],len(interval)])
        if i in dict_inter.keys():
            dict_inter[i] += 1
        else:
            dict_inter[i] = 1

In [42]:
discretized_ts = np.array(discretized_ts)

In [43]:
discretized_ts

array([[7188,    1,   10,   97],
       [ 430,    1,   10,   72],
       [3134,    1,   10,   66],
       ...,
       [7604, 7602,   10,   62],
       [7602, 7604,   10,   62],
       [7604, 7603,  -10,   62]])

In [44]:
len(np.unique(discretized_ts[:,:2]))

3783

In [45]:
new_df = pd.DataFrame(discretized_ts, columns=['u', 'i', 'label','ts'])

In [46]:
new_df

u     i  label  ts
0      7188     1     10  97
1       430     1     10  72
2      3134     1     10  66
3      3026     1     10  50
4      3010     1     10  48
...     ...   ...    ...  ..
24181  7604  7601     10  62
24182  7601  7604     10  62
24183  7604  7602     10  62
24184  7602  7604     10  62
24185  7604  7603    -10  62

[24186 rows x 4 columns]

In [47]:
sorted(dict_inter.values())

[4,
 4,
 4,
 5,
 6,
 6,
 7,
 8,
 9,
 11,
 11,
 11,
 11,
 12,
 12,
 12,
 14,
 14,
 16,
 17,
 18,
 18,
 19,
 19,
 20,
 21,
 28,
 29,
 31,
 32,
 35,
 44,
 52,
 61,
 66,
 66,
 72,
 72,
 72,
 77,
 78,
 78,
 84,
 89,
 90,
 90,
 93,
 95,
 99,
 99,
 105,
 106,
 107,
 107,
 107,
 108,
 111,
 111,
 117,
 118,
 119,
 123,
 125,
 126,
 131,
 139,
 142,
 148,
 151,
 152,
 153,
 154,
 154,
 155,
 166,
 169,
 171,
 173,
 174,
 177,
 181,
 193,
 198,
 204,
 205,
 206,
 207,
 208,
 209,
 215,
 219,
 224,
 225,
 227,
 229,
 232,
 235,
 246,
 249,
 249,
 252,
 254,
 261,
 261,
 263,
 264,
 271,
 276,
 280,
 286,
 287,
 289,
 294,
 299,
 303,
 304,
 307,
 309,
 310,
 314,
 318,
 320,
 320,
 323,
 326,
 328,
 340,
 349,
 446,
 456,
 524,
 650,
 904,
 1066,
 1431]

In [48]:
new_df.to_csv(file_save, index=False) 

In [49]:
file_save

'/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets/Bitcoin-Alpha/ml_Bitcoin-Alpha.csv'

In [50]:
len(np.unique(discretized_ts[:,:2]))

3783

## Bitcoin OTC

In [51]:
path_dst = '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets'
datadir = 'Bitcoin-OTC'
path_dst = join(path_dst, datadir)
file_save = join(path_dst,'ml_Bitcoin-OTC.csv')

In [52]:
path_src = '/share/DEEPLEARNING/datasets/graph_datasets/Rol'
file_src = 'bitcoinotc.csv'
path_src = join(path_src, file_src)

In [53]:
df = pd.read_csv(path_src,sep=',',header=None)

In [54]:
df

0     1  2             3
0         6     2  4  1.289242e+09
1         6     5  2  1.289242e+09
2         1    15  1  1.289243e+09
3         4     3  7  1.289245e+09
4        13    16  8  1.289254e+09
...     ...   ... ..           ...
35587  4499  1810  1  1.453612e+09
35588  2731  3901  5  1.453679e+09
35589  2731  4897  5  1.453679e+09
35590    13  1128  1  1.453680e+09
35591  1128    13  2  1.453684e+09

[35592 rows x 4 columns]

In [55]:
arr = df.values

In [56]:
arr

array([[6.00000000e+00, 2.00000000e+00, 4.00000000e+00, 1.28924191e+09],
       [6.00000000e+00, 5.00000000e+00, 2.00000000e+00, 1.28924194e+09],
       [1.00000000e+00, 1.50000000e+01, 1.00000000e+00, 1.28924314e+09],
       ...,
       [2.73100000e+03, 4.89700000e+03, 5.00000000e+00, 1.45367943e+09],
       [1.30000000e+01, 1.12800000e+03, 1.00000000e+00, 1.45367963e+09],
       [1.12800000e+03, 1.30000000e+01, 2.00000000e+00, 1.45368432e+09]])

In [59]:
ts = arr[:,3]

In [61]:
min(ts)

1289241911.72836

In [62]:
deb =  1289174400 # 8/11/2010

fin = 1453679940  # 24/1/2016

In [71]:
interval = []
st = deb + 2*week
while st < fin:
    interval.append(st)
    st += 2*week

In [72]:
len(interval)

135

In [74]:
interval[0] == deb + 2*week

True

In [75]:
start = deb # 7 novembre 2010 
# fin # 21 Janvier 2016
dict_inter = {}
discretized_ts = []

for l in arr:
    t = l[3]
    for i,inter in enumerate(interval):
        if t < inter:
            discretized_ts.append([l[0],l[1],l[2],i])
            if i in dict_inter.keys():
                dict_inter[i] += 1
            else:
                dict_inter[i] = 1
            break
    else:
        discretized_ts.append([l[0],l[1],l[2],len(interval)])
        if i in dict_inter.keys():
            dict_inter[i] += 1
        else:
            dict_inter[i] = 1

In [78]:
discretized_ts = np.array(discretized_ts,dtype=int)

In [79]:
discretized_ts

array([[   6,    2,    4,    0],
       [   6,    5,    2,    0],
       [   1,   15,    1,    0],
       ...,
       [2731, 4897,    5,  135],
       [  13, 1128,    1,  135],
       [1128,   13,    2,  135]])

In [82]:
new_df = pd.DataFrame(discretized_ts, columns=['u', 'i', 'label','ts'])

In [83]:
new_df.to_csv(file_save, index=False) 

In [84]:
file_save

'/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets/Bitcoin-OTC/ml_Bitcoin-OTC.csv'

In [85]:
len(discretized_ts)

35592

In [86]:
len(np.unique(discretized_ts[:,:2]))

5881

In [87]:
len(interval)

135