In [3]:
from os.path import join 

import pandas as pd
import numpy as np
import torch 



In [4]:
path_tbe = '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets'
dataset = 'CanParl'
path_dataset = join(path_tbe,dataset)

In [5]:
df_data = pd.read_csv(join(path_dataset,'ml_'+str(dataset)+'.csv'))

In [7]:
df_data

Unnamed: 0    u    i           ts  label    idx
0               0  384  353          0.0    0.0      1
1               1  411  353          0.0    0.0      2
2               2  676  353          0.0    0.0      3
3               3  467  353          0.0    0.0      4
4               4  120  353          0.0    0.0      5
...           ...  ...  ...          ...    ...    ...
74473       74473  695  398  410227200.0    0.0  74474
74474       74474  355  398  410227200.0    0.0  74475
74475       74475  444  398  410227200.0    0.0  74476
74476       74476   98  398  410227200.0    0.0  74477
74477       74477  542  398  410227200.0    0.0  74478

[74478 rows x 6 columns]

In [9]:
ts = df_data.ts.values

In [11]:
len(np.unique(ts))

14

In [12]:
np.unique(ts)

array([0.000000e+00, 3.153600e+07, 6.307200e+07, 9.469440e+07,
       1.262304e+08, 1.577664e+08, 1.893024e+08, 2.209248e+08,
       2.524608e+08, 2.839968e+08, 3.155328e+08, 3.471552e+08,
       3.786912e+08, 4.102272e+08])

In [13]:
ts = np.array([int(t) for t in ts])

In [15]:
np.unique(ts)

array([        0,  31536000,  63072000,  94694400, 126230400, 157766400,
       189302400, 220924800, 252460800, 283996800, 315532800, 347155200,
       378691200, 410227200])

## Flights 

In [16]:
path_tbe = '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets'
dataset = 'Flights'
path_dataset = join(path_tbe,dataset)

In [17]:
df_data = pd.read_csv(join(path_dataset,'ml_'+str(dataset)+'.csv'))

In [18]:
df_data

Unnamed: 0     u      i     ts  label      idx
0                 0  8332   8332    0.0    0.0        1
1                 1  8332    227    0.0    0.0        2
2                 2  1307   3981    0.0    0.0        3
3                 3  1307   2135    0.0    0.0        4
4                 4  5661   8399    0.0    0.0        5
...             ...   ...    ...    ...    ...      ...
1927140     1927140  3977    935  121.0    0.0  1927141
1927141     1927141  3977   8893  121.0    0.0  1927142
1927142     1927142  3977   4314  121.0    0.0  1927143
1927143     1927143  3977  10365  121.0    0.0  1927144
1927144     1927144  3977   3977  121.0    0.0  1927145

[1927145 rows x 6 columns]

In [19]:
ts = df_data.ts.values

In [20]:
ts = np.array([int(t) for t in ts])

In [21]:
len(np.unique(ts))

122

In [22]:
np.unique(ts)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121])

In [23]:
df_data.u.values

array([8332, 8332, 1307, ..., 3977, 3977, 3977])