In [17]:
import os
import torch

In [2]:
dir = '/share/DEEPLEARNING/datasets/graph_datasets/Towards_better/TG_network_datasets/RG17/rg17'

In [3]:
from torch_geometric_temporal import TwitterTennisDatasetLoader

In [4]:
name = ['rg17','uo17']
dataloader = TwitterTennisDatasetLoader(event_id=name[0])

In [5]:
dataset = dataloader.get_dataset()

In [6]:
dataset

In [13]:
type(dataset.__getitem__(1))

torch_geometric.data.data.Data

In [8]:
dataset.__getitem__(0).edge_attr 

tensor([2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 3., 2., 1., 1., 1., 1., 2., 2., 2., 1., 1., 1., 3.])

In [11]:
type(dataset)

torch_geometric_temporal.signal.dynamic_graph_temporal_signal.DynamicGraphTemporalSignal

In [12]:
dataset[0]

Data(x=[1000, 16], edge_index=[2, 89], edge_attr=[89], y=[1000])

In [9]:
dataset.__getitem__(0).x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])

In [18]:
torch.arange(dataset[0].x.shape[0])

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [10]:
dataset[0]

Data(x=[1000, 16], edge_index=[2, 89], edge_attr=[89], y=[1000])

In [58]:
total_edge = 0
for i in range(dataset.snapshot_count):
    
    total_edge += dataset.__getitem__(i).edge_index.shape[1]

In [59]:
total_edge

40839

In [60]:
n_snapshot = dataset.snapshot_count


In [61]:
n_snapshot

120

In [ ]:
n_snapshot = dataset.snapshot_count

for i in range(n_snapshot):
    

In [27]:
dataset[0:10]

In [28]:
dts_train = dataset[0:10]

In [29]:
dts_train

In [34]:
dts_train.snapshot_count

10

In [33]:
dts_train.__len__()

AttributeError: 'DynamicGraphTemporalSignal' object has no attribute '__len__'

In [36]:
dts_train[0].x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.]])